export const types = {
  AUTH_LOGIN: '[auth] AUTH_LOGIN',
  AUTH_LOGOUT: '[auth] AUTH_LOGOUT',
  AUTH_FETCHING_LOGIN: '[auth] AUTH_FETCHING_LOGIN',
  AUTH_ERROR: '[auth] AUTH_ERROR',
  CHAT_GET_REALTIME_USERS: '[chat] CHAT_GET_REALTIME_USERS',
  CHAT_GET_REALTIME_USERS_FETCH: '[chat] CHAT_GET_REALTIME_USERS_FETCH'
}